### ISSUE TITLE
2023 setup adjustments

### ISSUE THREAD

**Issue by HomeACcessoryKid** [doct0r0710/Esp32ThermalCam#2]
Hi, great invention!

January 2023 I have set up this system and I needed to adjust some things.
I hope others will find this useful.

I had to replace this header filename because the arduino IDE (2.0.3) has an alternative source for this library from `dvarrel`. The internal functions are the same.
```
- #include <ESPAsyncWebServer.h>
+ #include <ESPAsyncWebSrv.h>
```
This line needs to be removed. Without removing this line, you just freeze on the spot...
`- Wire.beginTransmission(MLX90640_I2CADDR_DEFAULT);`

I used two resistors of 4k7 for pull up on the SDA and SCL lines, but somehow this does not allow the ESP32-CAM to boot anymore, with the error:
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
```
by using GPIO2 as the `Vcc` source for pull-up I fixed that
```
+ #define I2C_PUP  2 // this is where to connect the 2x 4k7 pull up resistors
  log("Setting up bolometer");
+  pinMode(I2C_PUP, OUTPUT);
+  digitalWrite(I2C_PUP, HIGH);
```
the usage of the LEDs is not clear. With this, at least you know which is which.
```
#define FLASH_LED  4 // active on HIGH
#define SMALL_LED 33 // active on LOW
```

**Comment by HomeACcessoryKid** [comment]
Let me add that the library `dom-to-image` is not something that needs to be added to the Arduino code. Best change the `README.md` on that.

Also, the I2C clock seems also acceptable at 400kHz...

Also, the connector of the ESP32-CAM to the camera seems sensitive. I ran into an issue with the error `cam_hal: EV-VSYNC-OVF` rolling over the screen and the image collection failed.
After a lot of software attempts, the solution was to re-seat the connector!!

**Comment by HomeACcessoryKid** [comment]
If you feel to print an exclosure for this setup, consider this fusion360 file and the resulting 3mf files [heatcam.zip](https://github.com/doct0r0710/Esp32ThermalCam/files/10530515/heatcam.zip)

A few photos about how this turned out. Note I track GPIO15 to turn on and off the flash LED.
![IMG_6995](https://user-images.githubusercontent.com/22873922/215347145-f3775643-4332-4a73-aae7-559345f2f04d.jpg)
![IMG_6996](https://user-images.githubusercontent.com/22873922/215347179-7aa16ac9-12c2-4b26-bc6e-3d5318ea0a7c.jpg)
PS. my filament was a bit flaky, so the print didn't turn out pristine. But functional it is.

**Comment by doct0r0710** [comment]
I am really glad you like the code and having success with it. I haven't had luck with the stability of my setup and it stood unused until I repourposed the ESP32 board for a different project. 
With that, I am currently not in posession of a ESP32 board or a thermal module, so I can't test your modifications. However if you could put them in a Pull request, I'd merge it into the main branch. 
_(I'm also not too familiar with the Github ettiquette, I'm hoping the PR is what's needed here)_

I very much like the 3D printed case, it gives the feeling of a finished product. With your permission I'd also include the zip you provided in the main branch.

**Comment by HomeACcessoryKid** [comment]
permissions granted. You can also add the photos. I'll work on a PR.
Perhaps I can add those things in the PR and you just merge them?
I'll open a few more issues with other ideas...

**Comment by HomeACcessoryKid** [comment]
PR for code submitted.
Leaving photo and zip file to you for merging

**Comment by HomeACcessoryKid** [comment]
All these comments have been merged into the repository, so I'll close the issue.
Thanks for the welcoming spirit!
