### ISSUE TITLE
heat marker got mirrored

### ISSUE THREAD

**Issue by HomeACcessoryKid** [doct0r0710/Esp32ThermalCam#3]
Hi again, very happy about your repo so giving feedback and looking for advice.
Maybe others can chip in as well?

Anyhow, the marker works, except that it reports on a pixel that is mirrored horizontally.

My thing is not html and javascript, so no idea how to fix this...

**Comment by Kobbe1** [comment]
I never used the marker. But tried it now - and you are right - the measured point is indeed mirrored, so to measure a spot on the left you need to mark the same spot but on the right side of the screen and vice versa.
I guess it might be an easy fix, maybe around line 1001 in html.h?

**Comment by doct0r0710** [comment]
I think I see the problem, will provide a fix ASAP.

**Comment by doct0r0710** [comment]
Please, can someone check if the current version fixed this issue, so it can be closed?

**Comment by HomeACcessoryKid** [comment]
I have tested this and the issue is solved!
